import { LANGUAGES } from './languages.js';

const MAX_CHUNK=1200;
const EN={tagline:'Dictionary & translator',eyebrow:'Translation',hero:'Simple, private, on-device.',device:'On device',source:'Source language',target:'Target language',search:'Search languages…',input:'Input text',clear:'Clear',translation:'Translation',save:'Save',copy:'Copy',share:'Share',placeholder:'Your translation will appear here.',inputPH:'Type or paste text…',translate:'Translate',export:'Export',favorites:'Favorites',favoritesHint:'Saved translations',history:'History',historyHint:'Recent translations',about:'About',aboutHint:'Earth Dictionary',settings:'Settings',preferences:'Preferences',appLanguage:'App language',appLanguageHint:'Use any supported language for the interface.',theme:'Theme',themeHint:'Choose the look of the app.',system:'System',light:'Light',dark:'Dark',textSize:'Text size',textSizeHint:'Adjust readability.',animations:'Animations',animationsHint:'Use soft motion throughout the interface.',remember:'Remember languages',rememberHint:'Keep your last language pair.',clearHistory:'Clear local history',recent:'Recent translations',saved:'Saved translations',aboutText:'A minimal dictionary and on-device translator built for private, everyday language work.',createdBy:'Created by',model:'Translation model',version:'Version',use:'Use',remove:'Remove',noHistory:'No translations yet.',noFavorites:'No saved translations yet.'};
const FA={...EN,tagline:'واژه‌نامه و مترجم',eyebrow:'ترجمه',hero:'ساده، خصوصی و روی خود دستگاه.',device:'روی دستگاه',source:'زبان مبدأ',target:'زبان مقصد',search:'جستجوی زبان…',input:'متن ورودی',clear:'پاک کردن',translation:'ترجمه',save:'ذخیره',copy:'کپی',share:'اشتراک‌گذاری',placeholder:'ترجمه اینجا نمایش داده می‌شود.',inputPH:'متن را وارد یا جای‌گذاری کنید…',translate:'ترجمه',export:'خروجی',favorites:'ذخیره‌شده‌ها',favoritesHint:'ترجمه‌های ذخیره‌شده',history:'تاریخچه',historyHint:'ترجمه‌های اخیر',about:'درباره',aboutHint:'Earth Dictionary',settings:'تنظیمات',preferences:'ترجیحات',appLanguage:'زبان برنامه',appLanguageHint:'زبان رابط را انتخاب کنید.',theme:'پوسته',themeHint:'ظاهر برنامه را انتخاب کنید.',system:'سیستم',light:'روشن',dark:'تیره',textSize:'اندازه متن',textSizeHint:'خوانایی متن را تنظیم کنید.',animations:'انیمیشن‌ها',animationsHint:'حرکت‌های نرم رابط.',remember:'به‌خاطر سپاری زبان‌ها',rememberHint:'آخرین جفت زبان حفظ شود.',clearHistory:'پاک کردن تاریخچه محلی',recent:'ترجمه‌های اخیر',saved:'ترجمه‌های ذخیره‌شده',aboutText:'یک واژه‌نامه و مترجم مینیمال و روی دستگاه، برای استفاده روزمره و خصوصی.',createdBy:'ساخته‌شده توسط',model:'مدل ترجمه',version:'نسخه',use:'استفاده',remove:'حذف',noHistory:'هنوز ترجمه‌ای ثبت نشده است.',noFavorites:'هنوز ترجمه‌ای ذخیره نشده است.'};

const $=s=>document.querySelector(s), els={src:$('#sourceLanguage'),dst:$('#targetLanguage'),app:$('#appLanguage'),filter:$('#languageFilter'),input:$('#sourceText'),out:$('#resultText'),go:$('#translate'),status:$('#status'),count:$('#sourceCount'),bar:$('#progressBar'),wrap:$('#progressWrap'),toast:$('#toast'),splash:$('#splash'),overlay:$('#overlay'),history:$('#historyList'),favs:$('#favoritesList')};
const state={detected:'en',appLang:localStorage.getItem('earth_app_language')||'fa',nativeReady:false};
const pending=new Map();
let requestCounter=0;
let nativeReadyResolve,nativeReadyReject;
const nativeReadyPromise=new Promise((resolve,reject)=>{nativeReadyResolve=resolve;nativeReadyReject=reject});

window.earthNativeModelReady=(ok,message='')=>{state.nativeReady=!!ok;if(ok){els.status.textContent='M2M-100 · '+(strings()?.device||'On device');nativeReadyResolve();}else{nativeReadyReject(new Error(message||'Native M2M100 initialization failed.'));els.status.textContent=message||'Translation engine unavailable.';}};
window.earthNativeTranslationResult=(id,result,ok,message='')=>{const p=pending.get(id);if(!p)return;pending.delete(id);ok?p.resolve(result):p.reject(new Error(message||'Translation failed.'));};

const rtl=c=>['ar','fa','he','ps','sd','ur'].includes(c), name=c=>LANGUAGES.find(x=>x.code===c)?.name||c;
function strings(){return state.appLang==='fa'?FA:state.appLang==='en'?EN:null}
async function nativeTranslate(text,src,dst){if(!window.EarthNative)throw new Error('Native engine bridge is unavailable.');if(!state.nativeReady)await nativeReadyPromise;return new Promise((resolve,reject)=>{const id='r'+(++requestCounter);pending.set(id,{resolve,reject});try{window.EarthNative.translate(id,text,src,dst)}catch(e){pending.delete(id);reject(e)}})}
function opts(select,list){select.replaceChildren(...list.map(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;return o;}))}
function populate(){const q=els.filter.value.trim().toLowerCase(), list=q?LANGUAGES.filter(x=>(x.name+x.code).toLowerCase().includes(q)):LANGUAGES;opts(els.src,[['auto',state.appLang==='fa'?'تشخیص خودکار':'Auto detect'],...list.map(x=>[x.code,`${x.name} — ${x.code}`])]);opts(els.dst,list.map(x=>[x.code,`${x.name} — ${x.code}`]));opts(els.app,LANGUAGES.map(x=>[x.code,`${x.name} — ${x.code}`]));els.app.value=state.appLang;if(!els.dst.value)els.dst.value='en'}
function detect(t){if(/[پچژگک]/.test(t))return'fa';if(/[぀-ヿ]/.test(t))return'ja';if(/[가-힣]/.test(t))return'ko';if(/[一-鿿]/.test(t))return'zh';if(/[ऀ-ॿ]/.test(t))return'hi';if(/[Ѐ-ӿ]/.test(t))return'ru';if(/[֐-׿]/.test(t))return'he';if(/[اآأإئء-ي]/.test(t))return'ar';return'en'}
function chunks(t){const a=[];let s=t.trim();while(s.length>MAX_CHUNK){let i=s.lastIndexOf(' ',MAX_CHUNK);if(i<200)i=MAX_CHUNK;a.push(s.slice(0,i));s=s.slice(i).trim()}if(s)a.push(s);return a}
function read(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}function write(k,v){localStorage.setItem(k,JSON.stringify(v.slice(0,50)))}
function addHist(e){const a=read('earth_history').filter(x=>!(x.input===e.input&&x.output===e.output));a.unshift(e);write('earth_history',a);renderLists()}
function addFav(e){const a=read('earth_favorites');if(!a.some(x=>x.input===e.input&&x.output===e.output)){a.unshift(e);write('earth_favorites',a);toast(FA.saved||'Saved')}}
function renderLists(){els.history.innerHTML='';els.favs.innerHTML='';const draw=(el,list,empty,key)=>{if(!list.length){el.textContent=empty;el.className='empty-state';return}el.className='entry-list';list.forEach(x=>{const r=document.createElement('article');r.className='entry-row';r.innerHTML=`<div class="entry-meta">${name(x.source)} → ${name(x.target)}</div><div class="entry-input"></div><div class="entry-output"></div><div class="entry-actions"><button class="tiny-button" data-use>${EN.use}</button><button class="tiny-button ghost" data-remove>${EN.remove}</button></div>`;r.querySelector('.entry-input').textContent=x.input;r.querySelector('.entry-output').textContent=x.output;r.querySelector('[data-use]').onclick=()=>{els.src.value=x.source;els.dst.value=x.target;els.input.value=x.input;els.out.textContent=x.output;els.input.dispatchEvent(new Event('input'));close()};r.querySelector('[data-remove]').onclick=()=>{write(key,read(key).filter(y=>!(y.input===x.input&&y.output===x.output)));renderLists()};el.appendChild(r)})};draw(els.history,read('earth_history'),EN.noHistory,'earth_history');draw(els.favs,read('earth_favorites'),EN.noFavorites,'earth_favorites')}
function toast(t){els.toast.textContent=t;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),1600)}
function modal(id){els.overlay.hidden=false;const m=$(id);m.hidden=false;requestAnimationFrame(()=>{els.overlay.classList.add('show');m.classList.add('show')})}function close(){els.overlay.classList.remove('show');document.querySelectorAll('.modal.show').forEach(m=>m.classList.remove('show'));setTimeout(()=>{els.overlay.hidden=true;document.querySelectorAll('.modal').forEach(m=>m.hidden=true)},180)}
function theme(v){document.documentElement.dataset.theme=v;localStorage.setItem('earth_theme',v)}
function motion(v){document.documentElement.classList.toggle('motion-off',!v);localStorage.setItem('earth_motion',v?'1':'0')}
async function applyLanguage(){let s=strings();if(!s){s=localStorage.getItem('earth_ui_'+state.appLang)?JSON.parse(localStorage.getItem('earth_ui_'+state.appLang)):null;if(!s){s={...EN};for(const k of Object.keys(EN)){try{s[k]=await nativeTranslate(EN[k],'en',state.appLang)}catch{s[k]=EN[k]}}localStorage.setItem('earth_ui_'+state.appLang,JSON.stringify(s))}}document.querySelectorAll('[data-i18n]').forEach(n=>{if(s[n.dataset.i18n])n.textContent=s[n.dataset.i18n]});document.querySelectorAll('[data-i18n-placeholder]').forEach(n=>{if(s[n.dataset.i18nPlaceholder])n.placeholder=s[n.dataset.i18nPlaceholder]});document.documentElement.lang=state.appLang;document.documentElement.dir=rtl(state.appLang)?'rtl':'ltr';populate();renderLists()}

els.go.onclick=async()=>{const text=els.input.value.trim();if(!text)return;const source=els.src.value==='auto'?detect(text):els.src.value,target=els.dst.value;state.detected=source;if(source===target){els.out.textContent=text;return}els.go.disabled=true;els.status.textContent=`${FA.translation}…`;try{const parts=chunks(text),out=[];for(let i=0;i<parts.length;i++){out.push(await nativeTranslate(parts[i],source,target));els.bar.style.width=((i+1)/parts.length*100)+'%'}els.out.textContent=out.join('\n\n');els.out.classList.remove('reveal');void els.out.offsetWidth;els.out.classList.add('reveal');addHist({source,target,input:text,output:els.out.textContent,at:Date.now()})}catch(e){els.out.textContent=e?.message||'Translation failed.';console.error(e)}finally{els.go.disabled=false;els.wrap.hidden=true;els.status.textContent=strings()?.device||'On device'}};
els.input.oninput=()=>els.count.textContent=els.input.value.length.toLocaleString();els.filter.oninput=populate;els.clear.onclick=()=>{els.input.value='';els.out.textContent=FA.placeholder;els.count.textContent='0'};els.copy.onclick=async()=>{if(els.out.textContent.trim())await navigator.clipboard?.writeText(els.out.textContent);toast(FA.copy)};els.save.onclick=()=>{if(els.input.value.trim()&&els.out.textContent.trim()&&els.out.textContent!==FA.placeholder)addFav({source:els.src.value==='auto'?state.detected:els.src.value,target:els.dst.value,input:els.input.value,output:els.out.textContent,at:Date.now()})};els.share.onclick=async()=>{try{await navigator.share?.({title:'Earth Dictionary',text:els.out.textContent});toast(FA.share)}catch{}};els.export.onclick=()=>{const b=new Blob([els.out.textContent],{type:'text/plain'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='translation.txt';a.click();URL.revokeObjectURL(u)};els.src.onchange=()=>localStorage.setItem('earth_src',els.src.value);els.dst.onchange=()=>localStorage.setItem('earth_dst',els.dst.value);
els.app.onchange=async e=>{state.appLang=e.target.value;localStorage.setItem('earth_app_language',state.appLang);try{await applyLanguage();toast(FA.languageChanged||'Language updated')}catch(e){toast(e?.message||'Language update failed')}};$('#settingsButton').onclick=()=>modal('#settingsModal');$('#historyButton').onclick=()=>modal('#historyModal');$('#openHistory').onclick=()=>modal('#historyModal');$('#openFavorites').onclick=()=>modal('#favoritesModal');$('#openAbout').onclick=()=>modal('#aboutModal');els.overlay.onclick=close;document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=close);$('#themeSelect').onchange=e=>theme(e.target.value);$('#textSize').oninput=e=>{document.documentElement.style.setProperty('--scale',e.target.value);localStorage.setItem('earth_text_size',e.target.value)};$('#animations').onchange=e=>motion(e.target.checked);$('#rememberLanguages').onchange=e=>localStorage.setItem('earth_remember',e.target.checked?'1':'0');els.clearHistory.onclick=()=>{localStorage.removeItem('earth_history');renderLists();toast(FA.historyCleared)};
function init(){theme(localStorage.getItem('earth_theme')||'system');document.documentElement.style.setProperty('--scale',localStorage.getItem('earth_text_size')||'1');motion(localStorage.getItem('earth_motion')!=='0');populate();els.src.value=localStorage.getItem('earth_src')||'auto';els.dst.value=localStorage.getItem('earth_dst')||'en';renderLists();applyLanguage();setTimeout(()=>{els.splash.classList.add('hide');els.splash.setAttribute('aria-hidden','true')},650)}init();
